# Site settings
title: Daniël de Vries, MSc
email: contact@daniel-de-vries.com
description: > # this means to ignore newlines until "baseurl:"
  Lorem Ipsum
# baseurl: "/" # the subpath of your site, e.g. /blog/
url: "http://daniel-de-vries.com/" # the base hostname & protocol for your site
github_username:  daniel-de-vries
permalink: /blog/:year/:month/:title.html
gems:
  - jekyll-sitemap

# Build settings
markdown: kramdown
theme: minima
